// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    NavBar: typeof import('./src/components/nav-bar.vue')['default']
    NoData: typeof import('./src/components/no-data.vue')['default']
    VanDialog: typeof import('vant/es')['Dialog']
    VanField: typeof import('vant/es')['Field']
    VanPopup: typeof import('vant/es')['Popup']
    VanRate: typeof import('vant/es')['Rate']
  }
}

export { }
